his
js-tasks-ru/htmlcss-20240216_ea-shreyner pull request #6
Opened 2024-03-16 10:42 UTC by EAShreyner

2024-03-16 10:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-16 10:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-16 10:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 15:18 UTC, GSemikozov requested changes

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-rows: repeat(2, 1fr);
лишнее

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 39px;
margin-bottom

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-self: center;
align-self + justify-self лишнее, зато надо добавить margin-top: 3px

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    size: 20px;
font? font-size?

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: flex-start;
flex-end

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
это лишнее

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.hisogram__rectangle__1 {
модификаторы пишем через `_` --> .hisogram__rectangle_1. Только нахвания должны быть семантическими: хотя бы 3 модификатора по типу .hisogram__rectangle_small

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <span class="histogram__amount">50254</span>
при такой разметке histogram__amount надо вынести за пределы histogram__up и сделать div-ом.

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="hisogram__rectangle__1"></div>
модификаторы используем обязательно с тем ЧТО модифицируем, не самостоятельно: `hisogram__rectangle hisogram__rectangle_small`

2024-03-18 15:18 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="rectangle__2"></div>
ну и ниже то же самое

2024-03-20 13:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-20 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 299px;
лишнее

2024-03-20 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-around;
лишнее (у нас уже есть gap)

2024-03-20 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
это значение по умолчанию должно быть удалено

2024-03-21 14:53 UTC, EAShreyner commented on 04-lection2/01-histogram/histogram.css
> +    width: 299px;
исправлено

2024-03-21 14:53 UTC, EAShreyner commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-around;
исправлено

2024-03-24 14:45 UTC, GSemikozov requested changes

2024-03-24 14:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
все еще актуально

2024-04-01 17:45 UTC, merged